import type { AppProps } from "next/app";
import { Open_Sans, Roboto } from "@next/font/google";
import "../styles/globals.css";
import Head from "next/head";
import useCurrentRoute from "Hooks/useCurrentRoute";
import Layout from "Layout/Layout";
import { ThemeProvider, useTheme } from "next-themes";

const roboto = Roboto({
  weight: ["100", "400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

const OpenSans = Open_Sans({
  weight: ["300", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-opensans",
  display: "swap",
});

export default function App({ Component, pageProps }: AppProps) {
  const { theme } = useTheme();
  const Title = useCurrentRoute();

  return (
    <div
      className={`${theme} ${OpenSans.variable} ${roboto.variable} min-h-[1000px]`}
    >
      <Head>
        <title>{Title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <ThemeProvider attribute="class">
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ThemeProvider>
    </div>
  );
}
